eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:6001/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: GestionUserAmelJaouadi
          uri: lb://GestionUserAmelJaouadi 
          predicates:
            - Path=/GestionUserAmelJaouadi/**
          filters:
            - RewritePath=/GestionUserAmelJaouadi/(?<path>.*), /${path}
        - id: GestionAbonneeAmelJaouadi
          uri: lb://GestionAbonneeAmelJaouadi
          predicates:
            - Path=/GestionAbonneeAmelJaouadi/**
          filters:
            - RewritePath=/GestionAbonneeAmelJaouadi/(?<path>.*), /${path}
